/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

/**
 *
 * @author long
 */

import javax.swing.JOptionPane;
import Processes.LoanSlip;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.ResultSet;
import java.sql.Date;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;



public final class ILoanSlip extends javax.swing.JFrame {

    /**
     * Creates new form ILoanSlip
     */
    
     private final LoanSlip loansliptbl = new LoanSlip();
   
      
    public ILoanSlip() {
        initComponents();
        Calendar calen = Calendar.getInstance();
        this.borroweddatetxt.setDate(calen.getTime());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Idloansliptxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        numberofbook = new javax.swing.JTextField();
        okbtn = new javax.swing.JButton();
        borroweddatetxt = new com.toedter.calendar.JDateChooser();
        paydatetxt = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximizedBounds(new java.awt.Rectangle(532, 530, 530, 530));
        setMaximumSize(new java.awt.Dimension(532, 400));
        setMinimumSize(new java.awt.Dimension(532, 400));
        setPreferredSize(new java.awt.Dimension(532, 400));
        setResizable(false);
        setSize(new java.awt.Dimension(532, 400));

        Idloansliptxt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Idloansliptxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdloansliptxtActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Mã phiếu mượn: ");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaces/documents.png"))); // NOI18N
        jLabel2.setText("Nhập thông tin phiếu mượn");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Ngày mượn:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("Ngày trả:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("Số lượng sách:");

        numberofbook.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        numberofbook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberofbookActionPerformed(evt);
            }
        });

        okbtn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        okbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaces/add-documents.png"))); // NOI18N
        okbtn.setText("Nhập");
        okbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                okbtnMouseClicked(evt);
            }
        });
        okbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okbtnActionPerformed(evt);
            }
        });
        okbtn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                okbtnKeyPressed(evt);
            }
        });

        borroweddatetxt.setDateFormatString("dd/MM/yyyy");
        borroweddatetxt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        borroweddatetxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                borroweddatetxtMouseClicked(evt);
            }
        });

        paydatetxt.setDateFormatString("dd/MM/yyyy");
        paydatetxt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Idloansliptxt, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(borroweddatetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(paydatetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(okbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numberofbook, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel2)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Idloansliptxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(borroweddatetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(paydatetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numberofbook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(okbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        Idloansliptxt.getAccessibleContext().setAccessibleName("");
        jLabel3.getAccessibleContext().setAccessibleName("loandatelbl");
        jLabel4.getAccessibleContext().setAccessibleName("paydatelbl");
        jLabel5.getAccessibleContext().setAccessibleName("numberofbooklbl");
        numberofbook.getAccessibleContext().setAccessibleName("numbooktxt");
        okbtn.getAccessibleContext().setAccessibleName("okbtn");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void IdloansliptxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdloansliptxtActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_IdloansliptxtActionPerformed

    private void numberofbookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberofbookActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numberofbookActionPerformed
    
    
    
    private void okbtnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_okbtnKeyPressed
        // TODO add your handling code here:
     
    }//GEN-LAST:event_okbtnKeyPressed

    public java.sql.Date convertJavaDateToSqlDate(java.util.Date date) {
        return new java.sql.Date(date.getTime());  
    }
    
    
    
    private void okbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_okbtnActionPerformed

    private void okbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_okbtnMouseClicked
        // TODO add your handling code here:
            DateFormat days = new SimpleDateFormat("dd");
            DateFormat months = new SimpleDateFormat("MM");
            if (Idloansliptxt.getText().length() == 0 || numberofbook.getText().length() == 0 || borroweddatetxt.getDate() == null || paydatetxt.getDate() == null) 
            {
                JOptionPane.showMessageDialog(null, "Mời bạn nhập đẩy đủ tất cả thông tin trên", "Thông báo", 1);
                return;
            }
            
             
         
            else 
            {    
                if (Idloansliptxt.getText().length() != 6)
                {
                    JOptionPane.showMessageDialog(null, "Quy định của mã phiếu là 6 ký tự", "Thông báo", 1);
                    return;
                }
                
                if(Integer.parseInt(numberofbook.getText()) > 3)
                {
                    JOptionPane.showMessageDialog(null, "Bạn chỉ được mượn tối đa 3 cuốn sách", "Thông báo", 1);
                    return;
                }
                
                if (Integer.parseInt(days.format(borroweddatetxt.getDate())) > Integer.parseInt(days.format(paydatetxt.getDate())) && Integer.parseInt(months.format(borroweddatetxt.getDate())) == Integer.parseInt(months.format(paydatetxt.getDate())))
                {
                    JOptionPane.showMessageDialog(null, "Bạn đặt sai ngày giờ", "Thông báo", 1);
                    return;
                }
            }
            
                  try
                    {
                      loansliptbl.InsertdatatoSQL(Idloansliptxt.getText(), convertJavaDateToSqlDate(borroweddatetxt.getDate()), convertJavaDateToSqlDate(paydatetxt.getDate()), Integer.parseInt(numberofbook.getText()));
                      
                      Loanslipscreen l = new Loanslipscreen();
                      l.setVisible(true);
                      l.ClearData();
                      l.ShowData();
                      JOptionPane.showMessageDialog(null, "Thêm thành công", "Thông báo", 1);
                      this.dispose();
                      
                      
                    }
                  catch (SQLException e)
                    {       
                     JOptionPane.showMessageDialog(null, "Lỗi cơ sở dữ liệu", "Thông báo", 1);   
                    }
                  
        
    }//GEN-LAST:event_okbtnMouseClicked

    private void borroweddatetxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_borroweddatetxtMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_borroweddatetxtMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ILoanSlip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ILoanSlip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ILoanSlip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ILoanSlip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ILoanSlip().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField Idloansliptxt;
    public com.toedter.calendar.JDateChooser borroweddatetxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    public javax.swing.JTextField numberofbook;
    private javax.swing.JButton okbtn;
    public com.toedter.calendar.JDateChooser paydatetxt;
    // End of variables declaration//GEN-END:variables
}
