/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import Processes.*;
import com.orsoncharts.plot.PiePlot3D;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Date;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PiePlot;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.general.DefaultPieDataset;
import Databases.Connect;
import Processes.Reader;
import Processes.Book;
import Processes.DetailReceipt;
import Processes.IdentityCard;
import java.awt.Cursor;
import java.awt.Image;
import java.awt.Point;
import java.awt.Toolkit;
import java.io.File;
import javax.swing.ImageIcon;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.renderer.category.BarRenderer;
import org.jfree.data.jdbc.JDBCCategoryDataset;
/**
 *
 * @author long
 */
public class Library extends javax.swing.JFrame {

    public Connect cn = new Connect();
        /**
     * Creates new form Library
     */
    public Library() {
        initComponents();
        
        
    }
    
    public String[] getImages()
    {
        File file = new File("Interfaces");
        String[] imagelist = file.list();
        return imagelist;
    }
    
    
    public void showImages(int index)
    {
        String[] imageList = this.getImages();
        String imagename = imageList[index];
        ImageIcon icon = new ImageIcon(getClass().getResource("Interfaces/"+imagename));
        Image image = icon.getImage().getScaledInstance(jLabel1.getWidth(), jLabel1.getHeight(), Image.SCALE_SMOOTH);
        jLabel1.setIcon(new ImageIcon(image));
    }    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        readerinfobtn = new javax.swing.JButton();
        bookinfobtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 0, 102));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(new java.awt.Color(255, 0, 255));
        setResizable(false);

        readerinfobtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        readerinfobtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaces/contact-info.png"))); // NOI18N
        readerinfobtn.setText("THÔNG TIN THÀNH VIÊN");
        readerinfobtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                readerinfobtnMouseClicked(evt);
            }
        });

        bookinfobtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        bookinfobtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaces/book (1).png"))); // NOI18N
        bookinfobtn.setText("THÔNG TIN SÁCH");
        bookinfobtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookinfobtnMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaces/book.png"))); // NOI18N
        jLabel1.setText("THƯ VIỆN RÔ BI");
        jLabel1.setToolTipText("");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaces/letter.png"))); // NOI18N
        jButton1.setText("HƯỚNG DẪN ");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaces/statistics.png"))); // NOI18N
        jButton2.setText("THỐNG KÊ THÀNH VIÊN");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaces/statistics.png"))); // NOI18N
        jButton3.setText("THỐNG KÊ SÁCH");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaces/statistic.png"))); // NOI18N
        jButton4.setText("THỐNG KÊ DOANH THU");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Nhà phát triển: Nhóm 14 của trường Đại học Công Nghệ TP.HCM(HUTECH)");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel2MouseExited(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(readerinfobtn)
                            .addComponent(jButton2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton3)
                                .addGap(15, 15, 15)))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(117, 117, 117)
                                .addComponent(bookinfobtn)
                                .addGap(82, 82, 82))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton4)
                                .addGap(44, 44, 44))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(378, 378, 378))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(180, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(150, 150, 150))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(readerinfobtn)
                    .addComponent(bookinfobtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton2)
                        .addComponent(jButton4)))
                .addContainerGap())
        );

        readerinfobtn.getAccessibleContext().setAccessibleName("Readerinfobtn");
        bookinfobtn.getAccessibleContext().setAccessibleName("bookinfo");

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void readerinfobtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_readerinfobtnMouseClicked
        try {
            // TODO add your handling code here:
            Readerscrn r = new Readerscrn();
            r.setVisible(true);
            r.ClearData();
            r.ShowData();
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(Library.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_readerinfobtnMouseClicked
    
   
    
    public void Instructiontbl()
    {
       JOptionPane.showMessageDialog(null, "Chào các nhân viên đến với Thư viện Rô Bi. ", "BẢNG HƯỚNG DẪN", 1);
       JOptionPane.showMessageDialog(null, "Trong màn hình chính này sẽ 2 mục để quản lý chính đó là THÀNH VIÊN và SÁCH", "BẢNG HƯỚNG DẪN", 1);
       JOptionPane.showMessageDialog(null, "Trong phần quản lý  đọc giả nhân viên hỏi thông tin người đọc sách dựa trên thông tin của phần mềm để tạo THẺ THÀNH VIÊN cho người đọc cũng như phiếu phạt và phiếu mượn sách", "BẢNG HƯỚNG DẪN", 1);
       JOptionPane.showMessageDialog(null, "Về phần thông tin sách thì nhân viên sẽ hỏi thông tin của tác giả và cũng như thông tin của nhà xuất bản của một cuốn sách để điền thông tin thích hợp", "BẢNG HƯỚNG DẪN", 1);
       JOptionPane.showMessageDialog(null, "Mọi thao tác cơ bản như TẠO, XÓA, SỬA, CẬP NHẬT, TÌM KIẾM đều được.", "BẢNG HƯỚNG DẪN", 1);
       JOptionPane.showMessageDialog(null, "Khi nhân viên phải điền thông tin của người đọc rồi mới tạo THẺ THÀNH VIÊN và cũng như PHIẾU MƯỢN, PHIẾU PHẠT.", "BẢNG HƯỚNG DẪN", 1);
       JOptionPane.showMessageDialog(null, "Nhân viên có thể lấy tập tin EXCEL để đưa vào trong danh sách cửa sổ THÀNH VIÊN hoặc xuất ra tập tin EXCEL.", "BẢNG HƯỚNG DẪN", 1);
       JOptionPane.showMessageDialog(null, "NHƯNG LƯU Ý KHI NHẬP LIỆU TỪ EXCEL. NHÂN VIÊN CẦN NÊN NHẬP DẤU  '  ĐẰNG TRƯỚC SỐ HOẶC NGÀY TRONG EXCEL ĐỂ KHI NHẬP TẬP TIN VÀO TRONG SẼ TRÁNH BỊ LỖI ", "BẢNG HƯỚNG DẪN", 1);
    }
    
    private void bookinfobtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookinfobtnMouseClicked
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            Bookinfo b = new Bookinfo();
            b.setVisible(true);
            b.ClearDatabook();
            b.ClearDatapub();
            b.ClearDataBookInfo();
            b.ShowDatab();
            b.ShowDatapub();
            b.ShowDatabi();
            this.dispose();
            
        } catch (SQLException ex) {
            Logger.getLogger(Library.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bookinfobtnMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.Instructiontbl();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        try {
            // TODO add your handling code here:
            this.cn.connectSQL();
            String readerstatistic = "SELECT DATEFROMPARTS(YEAR(Expdate), MONTH(Expdate), DAY(Expdate)) AS Thờigian, COUNT(*) AS Sốlượngthànhviên  FROM Identitycard GROUP BY Expdate";
            JDBCCategoryDataset dataset = new JDBCCategoryDataset(this.cn.conn, readerstatistic);
            JFreeChart chart = ChartFactory.createLineChart("THỐNG KÊ THÀNH VIÊN", "Tháng", "Số lượng thành viên", dataset, PlotOrientation.VERTICAL, true, true, true);
            BarRenderer renderer = null;
            CategoryPlot plot = null;
            renderer = new BarRenderer();
            ChartFrame scrn = new ChartFrame("THỐNG KÊ THÀNH VIÊN", chart);
            scrn.setVisible(true);
            scrn.setSize(1000, 600);
        } catch (SQLException ex) {
            Logger.getLogger(Library.class.getName()).log(Level.SEVERE, null, ex);
        }
      
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            this.cn.connectSQL();
            String bookstatistic = "SELECT DATEFROMPARTS(YEAR(datepub), MONTH(datepub), DAY(datepub)) AS Thờigian, SUM(B.ammount) AS Sốlượngsách  FROM Book B GROUP BY B.datepub";
            JDBCCategoryDataset dataset = new JDBCCategoryDataset(this.cn.conn, bookstatistic);
            JFreeChart chart = ChartFactory.createLineChart("THỐNG KÊ SÁCH", "Tháng", "Số lượng sách", dataset, PlotOrientation.VERTICAL, true, true, true);
            BarRenderer renderer = null;
            CategoryPlot plot = null;
            renderer = new BarRenderer();
            ChartFrame scrn = new ChartFrame("THỐNG KÊ SÁCH", chart);
            scrn.setVisible(true);
            scrn.setSize(1000, 600);
        } catch (SQLException ex) {
            Logger.getLogger(Library.class.getName()).log(Level.SEVERE, null, ex);
        }
     
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        try {
            // TODO add your handling code here:
            this.cn.connectSQL();
            String prostatistic = "SELECT DATEFROMPARTS(YEAR(dr.FoundedIdencardDate), MONTH(dr.FoundedIdencardDate), DAY(dr.FoundedIdencardDate)) AS Thờigian, SUM(dr.Cost + fc.Cost) AS Tổngdoanhthu  FROM DetailReceipt dr, Finecard fc  GROUP BY dr.FoundedIdencardDate";
            JDBCCategoryDataset dataset = new JDBCCategoryDataset(this.cn.conn, prostatistic);
            JFreeChart chart = ChartFactory.createLineChart("THỐNG KÊ DOANH THU", "Tháng", "Tỏng doanh thu", dataset, PlotOrientation.VERTICAL, true, true, true);
            BarRenderer renderer = null;
            CategoryPlot plot = null;
            renderer = new BarRenderer();
            ChartFrame scrn = new ChartFrame("THỐNG KÊ THÀNH VIÊN", chart);
            scrn.setVisible(true);
            scrn.setSize(1000, 600);
        } catch (SQLException ex) {
            Logger.getLogger(Library.class.getName()).log(Level.SEVERE, null, ex);
        }
      
        
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        Credit cre = new Credit();
        cre.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
        // TODO add your handling code here:
      
    }//GEN-LAST:event_jLabel2MouseEntered

    private void jLabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseExited
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jLabel2MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Library.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Library.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Library.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Library.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Library().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bookinfobtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton readerinfobtn;
    // End of variables declaration//GEN-END:variables
}
